#=============================================================================
#=============================================================================

obj-$(CONFIG_HW_ANTENNA_BOARD_MATCH)  += antenna_board_match/
obj-$(CONFIG_HUAWEI_AUDIO) += audio/
obj-$(CONFIG_RIL_NETLINK_MODULE)   += riltcp/
obj-$(CONFIG_RIL_SIM_NETLINK_MODULE)   += rilsim/
obj-y   += connectivity/
obj-$(CONFIG_HUAWEI_HW_DEV_DCT)  += devdetect/
obj-y   += inputhub/
obj-$(CONFIG_MAXQ616_POWER_SWITCH) += irda/
obj-$(CONFIG_NFC_DEVICES)   += nfc/
obj-$(CONFIG_HW_WIFI)   += net/
obj-y   += power/
obj-y += hwpower/
obj-$(CONFIG_HUAWEI_DSM) += recovery/
obj-$(CONFIG_HUAWEI_SENSORS_INPUT_INFO)   += sensor/
obj-y   += storage/
obj-$(CONFIG_HUAWEI_TS)   += touthscreen/
obj-y   += touch_key/
obj-y   += usb/
obj-$(CONFIG_ANTENNA_BOARDID_GPIO_DETECT) += antenna_board_gpio_match/
obj-$(CONFIG_HUAWEI_VIBRATOR) += vibrator/
obj-$(CONFIG_MADAPT) += madapt/
obj-$(CONFIG_HUAWEI_IO_TRACING) += iotrace/
obj-y   += hw_led/
obj-$(CONFIG_DP_AUX_SWITCH) += dp_aux_switch/
obj-$(CONFIG_HW_DP_SOURCE) += dp_source/
obj-$(CONFIG_HUAWEI_VENDOR_EXCEPTION) += vendor_exception/
obj-$(CONFIG_HWDPS) += hwdps/
obj-$(CONFIG_MEM_INSPECT) += rmeminspect/
obj-y += comb_key/
obj-$(CONFIG_HWSDP) += hwsdp/
