obj-$(CONFIG_HW_BOOSTER) += netlink_handle.o hw_booster_common.o tcp_para_collec.o sock_destroy_handler.o
obj-$(CONFIG_HW_PACKET_FILTER_BYPASS) += hw_packet_filter_bypass.o
obj-$(CONFIG_HW_NETWORK_QOE) += wifi_para_collec.o ip_para_collec.o
obj-$(CONFIG_CHR_NETLINK_MODULE) += chr_manager.o
