obj-$(CONFIG_HISI_CLK)                  += clk-kirin-common.o
obj-$(CONFIG_HISI_CLK)                  += hisi-clkgate.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-ppll.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-fast-dvfs.o
obj-$(CONFIG_HISI_CLK_MAILBOX_SUPPORT)	+= hisi-clk-mailbox.o

obj-$(CONFIG_HISI_CLK)                  += clk-dvfs.o
obj-$(CONFIG_HISI_CLK)                  += hisi-clk-intr.o

obj-$(CONFIG_HISI_PERIDVFS)             += dvfs/
