# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux kernel.
#

obj-$(CONFIG_HAVE_HW_BREAKPOINT_ADDR_MASK) += hisi_arch_watchpoint.o

obj-$(CONFIG_HISI_WORKAROUND_MONITOR)	+= hisi_workaround_monitor.o
