obj-$(CONFIG_HISI_SLOW_PATH_COUNT) += slowpath_count.o
obj-$(CONFIG_HISI_PAGE_TRACE) += mem_trace.o buddy_track.o

obj-$(CONFIG_HISI_PAGECACHE_HELPER) += pagecache_manage.o pagecache_manage_interface.o
obj-$(CONFIG_PROCESS_RECLAIM)	+= process_reclaim.o
