#=============================================================================
#  wifi
#=============================================================================
EXTRA_CFLAGS += -Idriver/huawei_platform

obj-$(CONFIG_HW_BOOSTER) += booster/
obj-$(CONFIG_CHR_NETLINK_MODULE) += chr/
obj-$(CONFIG_HW_DPIMARK_MODULE) += hw_dpi_mark/
obj-y += hwril/
obj-$(CONFIG_HW_WIFI) += ipv4/
obj-$(CONFIG_HW_NETQOS_SCHED)  += netqos_sched/
obj-$(CONFIG_HW_NETWORK_AWARE)  += network_aware/
obj-$(CONFIG_HW_WAUDIO_MODULE) += waudio/
obj-$(CONFIG_NET)            += hw_event.o
