#sensor unification for differ platform
obj-$(CONFIG_HUAWEI_HALL_INPUTHUB) += hall/
obj-$(CONFIG_FINGERPRINT) += fingerprint/
obj-$(CONFIG_SENSORS_COLOR_AP) += color_sensor/
obj-y += hw_pmic/
obj-y += weld/
obj-${CONFIG_EXT_INPUTHUB} += ext_inputhub/
