ccflags-y += -Idrivers/devkit/audiokit/

obj-$(CONFIG_SWITCH) += switch/
obj-$(CONFIG_HUAWEI_TYPEC) += typec/
obj-$(CONFIG_TCPC_CLASS) += pd/
obj-$(CONFIG_SUPERSWITCH) += superswitch/
obj-$(CONFIG_POGO_PIN) += hw_pogopin/
obj-$(CONFIG_HUAWEI_YCABLE) += hw_ycable/
